using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GuerreroWeb.Models
{
    public class ModUsuarios
    {
        public int IdUsu { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string PWD { get; set; }
        public int IdPerfil { get; set; }
        public int IdDepto { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Estatus { get; set; }
    }
    public class UsuariosSuc
    {
        public int IdUsuSuc { get; set; }
        public int IdUsu { get; set; }
        public int IdSuc { get; set; }
    }
    public class VtUsuarios
    {
        public int IdUsu { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string PWD { get; set; }
        public int IdDepto { get; set; }
        public string Departamento { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Estatus { get; set; }
        public int IdPerfil { get; set; }
        public string Perfil { get; set; }
        public bool EntraCxc { get; set; }
        public bool CxcAdd { get; set; }
        public bool CxcMod { get; set; }
        public bool CxcCan { get; set; }
        public bool CxcDel { get; set; }
        public bool EntraVentas { get; set; }
        public bool VentaAdd { get; set; }
        public bool VentaMod { get; set; }
        public bool VentaCan { get; set; }
        public bool VentaDel { get; set; }
        public bool EntraInv { get; set; }
        public bool InvAdd { get; set; }
        public bool InvMod { get; set; }
        public bool InvCan { get; set; }
        public bool InvDel { get; set; }
        public bool EntraArticulos { get; set; }
        public bool ArticuloAdd { get; set; }
        public bool ArticuloMod { get; set; }
        public bool ArticuloDel { get; set; }
        public bool EntraLineas { get; set; }
        public bool LineasAdd { get; set; }
        public bool LineasMod { get; set; }
        public bool LineasDel { get; set; }
        public bool EntraCategoria { get; set; }
        public bool CatAdd { get; set; }
        public bool CatMod { get; set; }
        public bool CatDel { get; set; }
        public bool EntraMarcas { get; set; }
        public bool MarcasAdd { get; set; }
        public bool MarcasMod { get; set; }
        public bool MarcasDel { get; set; }
        public bool EntraModelos { get; set; }
        public bool ModelosAdd { get; set; }
        public bool ModelosMod { get; set; }
        public bool ModelosDel { get; set; }
        public bool EntraColores { get; set; }
        public bool ColoresAdd { get; set; }
        public bool ColoresMod { get; set; }
        public bool ColoresDel { get; set; }
        public bool EntraUnidad { get; set; }
        public bool UnidadAdd { get; set; }
        public bool UnidadMod { get; set; }
        public bool UnidadDel { get; set; }
        public bool EntraCompras { get; set; }
        public bool CompraAdd { get; set; }
        public bool CompraMod { get; set; }
        public bool CompraCan { get; set; }
        public bool CompraDel { get; set; }
        public bool EntraCxp { get; set; }
        public bool CxpAdd { get; set; }
        public bool CxpMod { get; set; }
        public bool CxpCan { get; set; }
        public bool CxpDel { get; set; }
        public bool EntraReportes { get; set; }
        public bool EntraRepCxc { get; set; }
        public bool EntraRepVen { get; set; }
        public bool EntraRepInv { get; set; }
        public bool EntraRepCom { get; set; }
        public bool EntraRepCxp { get; set; }
        public bool EntraWati { get; set; }
        public bool EntraWatiEnv { get; set; }
        public bool EntraWatiCons { get; set; }
        public bool EntraWatiPlan { get; set; }
        public bool EntraWatiAuto { get; set; }
        public bool WatiAdd { get; set; }
        public bool WatiDel { get; set; }
        public bool WatiMod { get; set; }
        public bool EntraConfiguraciones { get; set; }
        public bool EntraEmpresa { get; set; }
        public bool EmpresaMod { get; set; }
        public bool EntraSistema { get; set; }
        public bool EntraModulos { get; set; }
        public bool ModAdd { get; set; }
        public bool ModMod { get; set; }
        public bool ModDel { get; set; }
        public bool EntraMovtos { get; set; }
        public bool MovtosAdd { get; set; }
        public bool MovtosMod { get; set; }
        public bool MovtosDel { get; set; }
        public bool EntraFolios { get; set; }
        public bool FolioAdd { get; set; }
        public bool FolioMod { get; set; }
        public bool FolioDel { get; set; }
        public bool EntraUsuarios { get; set; }
        public bool UsuarioAdd { get; set; }
        public bool UsuarioMod { get; set; }
        public bool UsuarioDel { get; set; }
        public bool EntraPerfiles { get; set; }
        public bool PerfilAdd { get; set; }
        public bool PerfilMod { get; set; }
        public bool PerfilDel { get; set; }
        public bool EntraSucursales { get; set; }
        public bool SucursalAdd { get; set; }
        public bool SucursalMod { get; set; }
        public bool SucursalDel { get; set; }
        public bool EntraAlmacenes { get; set; }
        public bool AlmacenAdd { get; set; }
        public bool AlmacenMod { get; set; }
        public bool AlmacenDel { get; set; }
        public bool EntraDepto { get; set; }
        public bool DeptoAdd { get; set; }
        public bool DeptoMod { get; set; }
        public bool DeptoDel { get; set; }
        public bool EntraPaises { get; set; }
        public bool PaisAdd { get; set; }
        public bool PaisMod { get; set; }
        public bool PaisDel { get; set; }
        public bool EntraEstados { get; set; }
        public bool EstadoAdd { get; set; }
        public bool EstadoMod { get; set; }
        public bool EstadoDel { get; set; }
        public bool EntraCiudades { get; set; }
        public bool CiudadAdd { get; set; }
        public bool CiudadMod { get; set; }
        public bool CiudadDel { get; set; }
        public bool EntraColonias { get; set; }
        public bool ColoniaAdd { get; set; }
        public bool ColoniaMod { get; set; }
        public bool ColoniaDel { get; set; }
        public bool WatiConsAdd { get; set; }
        public bool WatiConsMod { get; set; }
        public bool WatiConsDel { get; set; }
        public bool WatiPlanAdd { get; set; }
        public bool WatiPlanMod { get; set; }
        public bool WatiPlanDel { get; set; }
		public bool EntraMovInv { get; set; }
		public bool EntraConta { get; set; }
		public bool ContaAdd { get; set; }
		public bool ContaMod { get; set; }
		public bool ContaCan { get; set; }
		public bool ContaDel { get; set; }
		public bool EntraCatConta { get; set; }
		public bool CatContaAdd { get; set; }
		public bool CatContaMod { get; set; }
		public bool CatContaDel { get; set; }
		public bool EntraFormPago { get; set; }
		public bool FPagoAdd { get; set; }
		public bool FPagoMod { get; set; }
		public bool FPagoDel { get; set; }
		public bool EntraMetPago { get; set; }
		public bool MetPagoAdd { get; set; }
		public bool MetPagoMod { get; set; }
		public bool MetPagoDel { get; set; }
		public bool EntraImp { get; set; }
		public bool ImpAdd { get; set; }
		public bool ImpMod { get; set; }
		public bool ImpDel { get; set; }
		public bool EntraRFiscal { get; set; }
		public bool RfiscalAdd { get; set; }
		public bool RfiscalMod { get; set; }
		public bool RfiscalDel { get; set; }
		public bool EntraRepConta { get; set; }
		public bool EntraClientes { get; set; }
		public bool CteAdd { get; set; }
		public bool CteMod { get; set; }
		public bool CteDel { get; set; }
		public bool EntraProv { get; set; }
		public bool ProvAdd { get; set; }
		public bool ProvMod { get; set; }
		public bool ProvDel { get; set; }
		public bool EntraCajas { get; set; }
		public bool CajaAdd { get; set; }
		public bool CajaMod { get; set; }
		public bool CajaDel { get; set; }
		public bool EntraTallas { get; set; }
		public bool TallaAdd { get; set; }
		public bool TallaMod { get; set; }
		public bool TallaDel { get; set; }
		public bool EntraFamilias { get; set; }
		public bool FamiliaAdd { get; set; }
		public bool FamiliaMod { get; set; }
		public bool FamiliaDel { get; set; }
	}
    public class Perfiles
    {
        public int IdPerfil { get; set; }
        public string Perfil { get; set; }
        public bool EntraCxc { get; set; }
        public bool CxcAdd { get; set; }
        public bool CxcMod { get; set; }
        public bool CxcCan { get; set; }
        public bool CxcDel { get; set; }
        public bool EntraVentas { get; set; }
        public bool VentaAdd { get; set; }
        public bool VentaMod { get; set; }
        public bool VentaCan { get; set; }
        public bool VentaDel { get; set; }
        public bool EntraInv { get; set; }
        public bool InvAdd { get; set; }
        public bool InvMod { get; set; }
        public bool InvCan { get; set; }
        public bool InvDel { get; set; }
        public bool EntraArticulos { get; set; }
        public bool ArticuloAdd { get; set; }
        public bool ArticuloMod { get; set; }
        public bool ArticuloDel { get; set; }
        public bool EntraLineas { get; set; }
        public bool LineasAdd { get; set; }
        public bool LineasMod { get; set; }
        public bool LineasDel { get; set; }
        public bool EntraCategoria { get; set; }
        public bool CatAdd { get; set; }
        public bool CatMod { get; set; }
        public bool CatDel { get; set; }
        public bool EntraMarcas { get; set; }
        public bool MarcasAdd { get; set; }
        public bool MarcasMod { get; set; }
        public bool MarcasDel { get; set; }
        public bool EntraModelos { get; set; }
        public bool ModelosAdd { get; set; }
        public bool ModelosMod { get; set; }
        public bool ModelosDel { get; set; }
        public bool EntraColores { get; set; }
        public bool ColoresAdd { get; set; }
        public bool ColoresMod { get; set; }
        public bool ColoresDel { get; set; }
        public bool EntraUnidad { get; set; }
        public bool UnidadAdd { get; set; }
        public bool UnidadMod { get; set; }
        public bool UnidadDel { get; set; }
        public bool EntraCompras { get; set; }
        public bool CompraAdd { get; set; }
        public bool CompraMod { get; set; }
        public bool CompraCan { get; set; }
        public bool CompraDel { get; set; }
        public bool EntraCxp { get; set; }
        public bool CxpAdd { get; set; }
        public bool CxpMod { get; set; }
        public bool CxpCan { get; set; }
        public bool CxpDel { get; set; }
        public bool EntraReportes { get; set; }
        public bool EntraRepCxc { get; set; }
        public bool EntraRepVen { get; set; }
        public bool EntraRepInv { get; set; }
        public bool EntraRepCom { get; set; }
        public bool EntraRepCxp { get; set; }
        public bool EntraWati { get; set; }
        public bool EntraWatiEnv { get; set; }
        public bool EntraWatiCons { get; set; }
        public bool EntraWatiPlan { get; set; }
        public bool EntraWatiAuto { get; set; }
        public bool WatiAdd { get; set; }
        public bool WatiDel { get; set; }
        public bool WatiMod { get; set; }
        public bool EntraConfiguraciones { get; set; }
        public bool EntraEmpresa { get; set; }
        public bool EmpresaMod { get; set; }
        public bool EntraSistema { get; set; }
        public bool EntraModulos { get; set; }
        public bool ModAdd { get; set; }
        public bool ModMod { get; set; }
        public bool ModDel { get; set; }
        public bool EntraMovtos { get; set; }
        public bool MovtosAdd { get; set; }
        public bool MovtosMod { get; set; }
        public bool MovtosDel { get; set; }
        public bool EntraFolios { get; set; }
        public bool FolioAdd { get; set; }
        public bool FolioMod { get; set; }
        public bool FolioDel { get; set; }
        public bool EntraUsuarios { get; set; }
        public bool UsuarioAdd { get; set; }
        public bool UsuarioMod { get; set; }
        public bool UsuarioDel { get; set; }
        public bool EntraPerfiles { get; set; }
        public bool PerfilAdd { get; set; }
        public bool PerfilMod { get; set; }
        public bool PerfilDel { get; set; }
        public bool EntraSucursales { get; set; }
        public bool SucursalAdd { get; set; }
        public bool SucursalMod { get; set; }
        public bool SucursalDel { get; set; }
        public bool EntraAlmacenes { get; set; }
        public bool AlmacenAdd { get; set; }
        public bool AlmacenMod { get; set; }
        public bool AlmacenDel { get; set; }
        public bool EntraDepto { get; set; }
        public bool DeptoAdd { get; set; }
        public bool DeptoMod { get; set; }
        public bool DeptoDel { get; set; }
        public bool EntraPaises { get; set; }
        public bool PaisAdd { get; set; }
        public bool PaisMod { get; set; }
        public bool PaisDel { get; set; }
        public bool EntraEstados { get; set; }
        public bool EstadoAdd { get; set; }
        public bool EstadoMod { get; set; }
        public bool EstadoDel { get; set; }
        public bool EntraCiudades { get; set; }
        public bool CiudadAdd { get; set; }
        public bool CiudadMod { get; set; }
        public bool CiudadDel { get; set; }
        public bool EntraColonias { get; set; }
        public bool ColoniaAdd { get; set; }
        public bool ColoniaMod { get; set; }
        public bool ColoniaDel { get; set; }
        public bool WatiConsAdd { get; set; }
        public bool WatiConsMod { get; set; }
        public bool WatiConsDel { get; set; }
        public bool WatiPlanAdd { get; set; }
        public bool WatiPlanMod { get; set; }
        public bool WatiPlanDel { get; set; }
		public bool EntraMovInv { get; set; }
		public bool EntraConta { get; set; }
		public bool ContaAdd { get; set; }
		public bool ContaMod { get; set; }
		public bool ContaCan { get; set; }
		public bool ContaDel { get; set; }
		public bool EntraCatConta { get; set; }
		public bool CatContaAdd { get; set; }
		public bool CatContaMod { get; set; }
		public bool CatContaDel { get; set; }
		public bool EntraFormPago { get; set; }
		public bool FPagoAdd { get; set; }
		public bool FPagoMod { get; set; }
		public bool FPagoDel { get; set; }
		public bool EntraMetPago { get; set; }
		public bool MetPagoAdd { get; set; }
		public bool MetPagoMod { get; set; }
		public bool MetPagoDel { get; set; }
		public bool EntraImp { get; set; }
		public bool ImpAdd { get; set; }
		public bool ImpMod { get; set; }
		public bool ImpDel { get; set; }
		public bool EntraRFiscal { get; set; }
		public bool RfiscalAdd { get; set; }
		public bool RfiscalMod { get; set; }
		public bool RfiscalDel { get; set; }
		public bool EntraRepConta { get; set; }
		public bool EntraClientes { get; set; }
		public bool CteAdd { get; set; }
		public bool CteMod { get; set; }
		public bool CteDel { get; set; }
		public bool EntraProv { get; set; }
		public bool ProvAdd { get; set; }
		public bool ProvMod { get; set; }
		public bool ProvDel { get; set; }
		public bool EntraCajas { get; set; }
		public bool CajaAdd { get; set; }
		public bool CajaMod { get; set; }
		public bool CajaDel { get; set; }
		public bool EntraTallas { get; set; }
		public bool TallaAdd { get; set; }
		public bool TallaMod { get; set; }
		public bool TallaDel { get; set; }
		public bool EntraFamilias { get; set; }
		public bool FamiliaAdd { get; set; }
		public bool FamiliaMod { get; set; }
		public bool FamiliaDel { get; set; }
	}
    public class VtPerfiles
    {
        public int IdPerfil { get; set; }
        public string Perfil { get; set; }
        public int Usuario { get; set; }
    }
    public class SpVtPerfiles
    {
        public string NomCampo { get; set; }
        public string Descripcion { get; set; }
        public int IdPerfil { get; set; }
        public string Perfil { get; set; }
        public bool Valor { get; set; }
        public string IdNodo {  get; set; }
        public string IdNodoPadre { get; set; }
    }
    public class VtUsuarioSuc
    {
		public int IdUsuSuc { get; set; }
		public int IdSuc { get; set; }
		public string Sucursal { get; set; }
		public string Nombre { get; set; }
		public int IdUsu { get; set; }
	}
}